name = "portfolio-2025"
type = "javascript"

[build]
command = "npm run build"
pages_build_output_dir = "build/client"

[env.production]
workers_dev = true
kv_namespaces = [
  { id = "MY_KV", binding="MY_KV" }
]
